//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "youtubePlaylistDetails"
	/// <summary>Youtube Playlist Details</summary>
	public partial interface IYoutubePlaylistDetails : IPublishedContent
	{
		/// <summary>Playlist Id</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string YoutubePlaylistId { get; }

		/// <summary>Playlist Url</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string YoutubePlaylistUrl { get; }
	}

	/// <summary>Youtube Playlist Details</summary>
	[PublishedModel("youtubePlaylistDetails")]
	public partial class YoutubePlaylistDetails : PublishedContentModel, IYoutubePlaylistDetails
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "youtubePlaylistDetails";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<YoutubePlaylistDetails, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public YoutubePlaylistDetails(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Playlist Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("youtubePlaylistId")]
		public string YoutubePlaylistId => GetYoutubePlaylistId(this);

		/// <summary>Static getter for Playlist Id</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetYoutubePlaylistId(IYoutubePlaylistDetails that) => that.Value<string>("youtubePlaylistId");

		///<summary>
		/// Playlist Url: Copy and paste url to the youtube playlist
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("youtubePlaylistUrl")]
		public string YoutubePlaylistUrl => GetYoutubePlaylistUrl(this);

		/// <summary>Static getter for Playlist Url</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetYoutubePlaylistUrl(IYoutubePlaylistDetails that) => that.Value<string>("youtubePlaylistUrl");
	}
}
